# .goreleaser.yaml
builds:
  - binary: live-server
    env:
    - CGO_ENABLED=0
    ldflags:
    - -X github.com/coolapso/go-live-server/cmd.Version={{.Version}}

aurs:
  - name: go-live-server
    homepage: "https://github.com/coolapso/go-live-server"
    description: "Simple development webserver with live reload"
    maintainers:
      - "coolapso <coolapso@coolapso.tech>"

    license: "MIT"
    private_key: "{{ .Env.AUR_KEY }}"
    git_url: "ssh://aur@aur.archlinux.org/go-live-server-bin.git"
    skip_upload: auto

    # Git author used to commit to the repository.
    commit_author:
      name: goreleaserbot
      email: bot@goreleaser.com

announce:
  discord:
    enabled: true
